name: Build Kernel

on:
  push:
    branches:
      - android17-XD
  workflow_dispatch:
    inputs:
      device:
        description: 'Target Device Code (设备代号)'
        required: true
        default: 'thyme'
        type: choice
        options:
          - thyme
          - alioth
          - lmi
          - pipa
          - apollo
      ksu:
        description: 'Enable KernelSU'
        required: true
        type: boolean
        default: true
      target_os:
        description: 'Target OS'
        required: true
        default: 'miui'
        type: choice
        options:
          - aosp
          - miui
          - both

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y ccache clang lld make git wget curl p7zip-full

      - name: Prepare build environment
        run: |
          export CCACHE_DIR=${{ github.workspace }}/.ccache
          export CCACHE_MAXSIZE=10G
          echo "CCACHE_DIR=${CCACHE_DIR}" >> $GITHUB_ENV

      - name: Run build script
        id: run_build
        run: |
          echo "Execute ./build.sh with args"
          ARGS=""
          if [ "${{ github.event.inputs.ksu }}" = "true" ]; then
            ARGS="$ARGS ksu"
          fi
          if [ "${{ github.event.inputs.target_os }}" != "both" ]; then
            ARGS="$ARGS ${{ github.event.inputs.target_os }}"
          fi
          echo "Build args: $ARGS"
          ./build.sh $ARGS

      - name: List all files for debug
        run: ls -laR

      - name: Upload Flashable ZIP
        uses: actions/upload-artifact@v7
        with:
          name: Kernel-${{ github.event.inputs.device }}-${{ github.event.inputs.target_os }}
          path: MagicTime-*/MagicTime-*.zip
          compression-level: 0
